name: Sync to Cloudflare KV

on:
  push:
    branches: [main]
    paths: ['lists/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate JSON
        run: |
          npm install -g ajv-cli
          find lists -name "*.json" -type f -exec ajv validate -s schema/category-schema.json -d {} \;
      
      - name: Process and Upload Files to KV
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: |
            for file in lists/*.json; do
              filename=$(basename "$file" .json)
              echo "Processing $filename"
              wrangler kv:key put --namespace-id=${{ secrets.KV_NAMESPACE_ID }} "$filename" --value="$(cat $file)"
            done
