name: Sync to Cloudflare KV

on:
  push:
    branches: [main]
    paths: ['lists/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Validate JSON
        run: |
          npm install -g ajv-cli
          find lists -name "*.json" -type f -exec ajv validate -s schema/category-schema.json -d {} \;
      
      # Upload categories.json
      - name: Upload categories
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: kv:key put --namespace-id=${{ secrets.KV_NAMESPACE_ID }} "categories" --path="./lists/categories.json"
      
      # Upload betting.json
      - name: Upload betting list
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: kv:key put --namespace-id=${{ secrets.KV_NAMESPACE_ID }} "betting" --path="./lists/betting.json"
